repos:
  # - repo: https://github.com/zricethezav/gitleaks
  #   rev: v8.12.0
  #   hooks:
  #     - id: gitleaks

  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
      - id: trailing-whitespace # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md] # keep hard linebreaks in md files
      - id: no-commit-to-branch
        args: [--branch, gh-pages] # dont commit directly to gh-pages (done through actions)
